"""mesada como alternativa ao valor da hora

Revision ID: 2e16870d8e56
Revises: bfe11a2741aa
Create Date: 2026-08-20 13:43:17.884975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e16870d8e56'
down_revision: Union[str, Sequence[str], None] = 'bfe11a2741aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default` não é decoração: o SQLite recusa adicionar coluna NOT
    # NULL a uma tabela que já tem linhas sem dizer com que valor preenchê-las.
    # E o valor certo é "work" — toda conta existente foi criada quando só
    # existia o modo trabalho.
    op.add_column(
        'users',
        sa.Column('income_mode', sa.String(length=12), nullable=False, server_default='work'),
    )
    op.add_column('users', sa.Column('allowance_cents', sa.Integer(), nullable=True))
    op.add_column(
        'users',
        sa.Column('allowance_period', sa.String(length=8), nullable=False, server_default='month'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowance_period')
    op.drop_column('users', 'allowance_cents')
    op.drop_column('users', 'income_mode')
    # ### end Alembic commands ###
