"""token do atalho do iphone

Revision ID: bfe11a2741aa
Revises: a1118ab8027b
Create Date: 2026-08-18 19:13:38.659893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe11a2741aa'
down_revision: Union[str, Sequence[str], None] = 'a1118ab8027b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shortcut_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_shortcut_token'), 'users', ['shortcut_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_shortcut_token'), table_name='users')
    op.drop_column('users', 'shortcut_token')
    # ### end Alembic commands ###
